Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,23 +1,43 @@
-name: deploy
-
 on:
   push:
     branches:
       - Actions
-
+name: Deploy to Salesforce Production
 jobs:
   deploy:
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout source code
+      - name: Checkout
         uses: actions/checkout@v2
-      - name: Install Salesforce CLI
-        uses: actions/setup-node@v1
+
+      - name: Setup Node
+        uses: actions/setup-node@v2
         with:
-          node-version: 14
-      - name: Authorize target org
+          node-version: "16.x"
+
+      - name: Install Dependencies
         run: |
-          echo ${{ secrets.SFDX_URL }} | base64 -d > jwt.key
-          sfdx force:auth:jwt:grant --clientid ${{ secrets.TARGET_ORG_CONSUMER_KEY }} --jwtkeyfile jwt.key --username ${{ secrets.TARGET_ORG_USERNAME }} --setdefaultdevhubusername -a target
-      - name: Deploy source code
-        run: sfdx force:source:deploy --sourcepath force-app --targetusername target --json
+          npm install -g sfdx-cli
+          #npm install gfarb/sfdx-deploy@v1
+          
+      - name: 'Populate auth file with DEVHUB_SFDX_URL secret'
+        shell: bash
+        run: |
+            echo ${{ secrets.DEVHUB_SFDX_URL}} > ./DEVHUB_SFDX_URL.txt
+            secretFileSize=$(wc -c "./DEVHUB_SFDX_URL.txt" | awk '{print $1}')
+            if [ $secretFileSize == 1 ]; then
+                echo "Missing DEVHUB_SFDX_URL secret. Is this workflow running on a fork?";
+                exit 1;
+            fi
+
+      - name: Authenticate Dev Hub
+        run: sfdx auth:sfdxurl:store -f ./DEVHUB_SFDX_URL.txt -a devhub -d
+
+      - name: Build, Test & Deploy
+        uses: gfarb/sfdx-deploy@v1
+        env:
+          TARGET_USERNAME: devhub
+          SOURCE_PATH: force-app
+          DESTRUCTIVE_CHANGES: destructive-changes
+          TEST_LEVEL: RunLocalTests
+          WAIT: 200
